Feature/oh my class/oh my class#36 implement o auth2.0 into backend for session handling
Oh-my-class/oh-my-backend pull request #12
Opened 2022-09-30 13:56 UTC by Z-100

Implemented JWT-token validation: access- & refreshtoken.

2022-09-30 13:56 UTC, Z-100 commented
close Oh-my-class/oh-my-class#36
close Oh-my-class/oh-my-class#33

2022-09-30 13:59 UTC, Z-100 commented on src/main/resources/application.yml
> +constants:
Will be further split, once we have all the properties needed.

2022-10-01 20:38 UTC, Lezurex requested changes

2022-10-01 20:38 UTC, Lezurex commented on src/main/java/com/ohmyclass/api/components/user/controller/IUserController.java
> +	@GetMapping("/user/get")
@GetMapping("/user") would be correct. Different HTTP-verbs can be on the same route.

2022-10-01 20:38 UTC, Lezurex commented on src/main/java/com/ohmyclass/api/components/user/controller/IUserController.java
> +	@PostMapping("/user/update")
To update use the PUT verb and also update the URL to just /user accordingly.

2022-10-01 20:38 UTC, Lezurex commented on src/main/java/com/ohmyclass/api/components/user/controller/IUserController.java
> +	@DeleteMapping("/user/delete")
Same here. Just /user

2022-10-01 20:38 UTC, Lezurex commented on src/main/java/com/ohmyclass/api/components/user/controller/IUserController.java
> +	@PutMapping("/auth/register")
Strictly speaking, this should be a POST mapping, as we create a new ressource.

2022-10-01 20:38 UTC, Lezurex commented on src/main/java/com/ohmyclass/api/components/user/service/crud/impl/UserService.java
> +		userRepo.save(userMapper.inDTOToEntity(userIn));
I guess you wanted to use the now unused private method **saveUser** here? Otherwise, the password is saved without being hashed, afaik.

2022-10-01 20:38 UTC, Lezurex commented on src/main/java/com/ohmyclass/api/components/user/service/mapper/AUserMapper.java
> +	abstract public UserOutDTO entityToOutDTO(@NotNull User user);
Just a minor note on code style: public comes before abstract.

2022-10-03 06:47 UTC, Lezurex approved these changes
very gud ser

2022-10-04 06:12 UTC, Lezurex approved these changes
now wörk hopefully

2022-10-04 06:13 UTC, merged